version: '2'
services:
    tex:
        build: "tex_custom"
        image: "tex_custom"
        restart: "no"
        #expose:
        #    - "80"
        volumes:
            - ./work:/work/

    # グラフ描画用_Gnuplot_コンテナ
    gnuplot:
        build: "gnuplot_custom"
        image: "gnuplot_custom"
        restart: "no"
        volumes:
            - ./work:/work/
